cc_library(
    name = "di",
    hdrs = [
        "Settings.hpp",
        "Factory.hpp",
        "Dispatcher.hpp",
        "TagDispatcher.hpp",
        "RuntimeSingleton.hpp",
    ],
    include_prefix = "di",
    visibility = ["//visibility:public"],
)

